Savename = gw190521_tests/092223_test1
Root = /home/simona.miller/time-domain-gw-inference/

Nproc = 32

executable = $(Root)/scripts/run_sampler.py
universe = vanilla
arguments = "--ncpu $(Nproc) --nsteps 50000 --nwalkers 512 -o $(Savename).h5"

request_cpus = $(Nproc)
request_memory = 4 GB
request_disk = 50000
accounting_group = ligo.dev.o4.cbc.testgr.tiger

log = $(Root)/condor/logs/$(Savename).log
output = $(Root)/condor/logs/$(Savename).out
error = $(Root)/condor/logs/$(Savename).err

getenv = True

queue