RunMode = pre
Savename = gw190521_tests/092723_test_$(RunMode)_0M
Root = /home/simona.miller/time-domain-gw-inference/

Nproc = 16

executable = $(Root)/scripts/run_sampler.py
universe = vanilla
arguments = "--ncpu $(Nproc) --nsteps 40000 --nwalkers 512 -o $(Savename).h5 -m $(RunMode) --resume"

request_cpus = $(Nproc)
request_memory = 4 GB
request_disk = 5000
accounting_group = ligo.dev.o4.cbc.testgr.tiger

log = $(Root)/condor/logs/$(Savename).log
output = $(Root)/condor/logs/$(Savename).out
error = $(Root)/condor/logs/$(Savename).err

getenv = True

queue